services:
  kotnost-bot:
    build: .
    container_name: kotnost-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - SQLITE_PATH=/app/data/kotnost.sqlite
    dns:
      - 1.1.1.1
      - 8.8.8.8
